repos:
- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
  - id: isort
    name: isort (python)
  - id: isort
    name: isort (cython)
    types: [cython]
  - id: isort
    name: isort (pyi)
    types: [pyi]
- repo: https://github.com/psf/black
  rev: 21.4b2
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=10000]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: name-tests-test
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements
  - id: check-ast
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: no-commit-to-branch
- repo: https://github.com/pycqa/flake8
  rev:  3.9.1
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy
    additional_dependencies: [pydantic==1.8.1]
