version: "3.8"

services:
  postgres:
    container_name: pawtrails_postgres
    image: postgres:13
    env_file: .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pawtrails
    #restart: unless-stopped # Alternatively use always

  pgadmin:
    depends_on:
      - postgres
    container_name: pawtrails_pgadmin
    image: dpage/pgadmin4:5
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - pawtrails
    #restart: unless-stopped # Alternatively use always

  backend:
    depends_on:
      - postgres
      - pgadmin
    container_name: pawtrails_backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    env_file: .env
    ports:
      - "80:80"
    networks:
      - pawtrails
    #restart: unless-stopped # Alternatively use always

volumes:
  postgres:
  pgadmin:

networks:
  pawtrails:
    driver: bridge
