version: '3.4'

services:
  neo4j:
    container_name: pawtrails_neo4j
    image: neo4j:4.1
    env_file: .env
    healthcheck:
      test: wget http://pawtrails_neo4j:7474/browser -O -
      interval: 1s
      timeout: 1s
      retries: 25
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/var/lib/neo4j/data
    networks:
      - pawtrails

  backend:
    container_name: pawtrails_backend
    image: pawtrails_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
      neo4j:
        condition: service_healthy
    command: ["sh", "-c", "ls & pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./app:/app/app
    networks:
      - pawtrails

volumes:
  neo4j_data:

networks:
  pawtrails:
    driver: bridge
