version: "3.8"

services:
  neo4j:
    container_name: pawtrails_neo4j
    image: neo4j:4.1
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_default__database=pawtrails
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    healthcheck:
      test: wget http://pawtrails_neo4j:7474/browser -O -
      interval: 1s
      timeout: 1s
      retries: 25
    ports:
        - 7474:7474
        - 7687:7687
    volumes:
        - neo4j_data:/var/lib/neo4j/data
    networks:
      - pawtrails

  backend:
    depends_on:
      neo4j:
        condition: service_healthy
    container_name: pawtrails_backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    env_file: .env
    ports:
      - 80:80
    networks:
      - pawtrails

volumes:
  neo4j_data:

networks:
  pawtrails:
    driver: bridge
