version: '3.8'

services:
  postgres:
    container_name: pawtrail_postgres
    image: postgres:13
    env_file: .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pawtrail
    restart: unless-stopped # Alternatively use always

  pgadmin:
    depends_on: 
      - postgres
    container_name: pawtrail_pgadmin
    image: dpage/pgadmin4:5
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - pawtrail
    restart: unless-stopped # Alternatively use always

volumes:
  postgres:
  pgadmin:

networks:
  pawtrail:
    driver: bridge
